<a href="https://colab.research.google.com/github/joannafan0518/Python_Bootcamp/blob/day-4-exercise/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [8]:
# Your code goes here
class Book:
    def __init__(self, title, author, pages, price):
        self.title = title
        self.author = author
        self.pages = pages
        self.set_price(price)

    def get_price(self):
        return self.price

    def set_price(self, price):
        if not isinstance(price, (int, float)):
            raise ValueError("Price must be numeric.")
        self.price = price

In [9]:
b1 = Book('Practical Programming', 'Gries, Campbell, Montojo', 383, 50)
b2 = Book('Building a Career in Data Science', 'Robinson, Nolis', 322, 40)

In [10]:
b1.get_price()

50

In [11]:
b2.get_price()

40

#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [16]:
# Your code goes here
class Phone:
    def __init__(self, model, id, name, brand, price):
        self.set_model = model
        self.set_id = id
        self.set_name = name
        self.set_brand = brand
        self.set_price = price

    def get_model(self):
        return self._model

    def get_id(self):
        return self._id

    def get_name(self):
        return self._name

    def get_brand(self):
        return self._brand

    def get_price(self):
        return self._price

    def set_price(self, price):
        if not isinstance(price, (int, float)):
            raise ValueError("Price must be numeric.")
        self._price = price

    def calculate_total(self, tax):
        return self._price + (self._price * tax)

In [17]:
phone = Phone("iPhone 14 pro", 1, "iPhone", "Apple", 999)

In [18]:
phone.get_price

<bound method Phone.get_price of <__main__.Phone object at 0x7d566f99b320>>

## Numpy

In [19]:
import numpy as np

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [24]:
# Your code goes here
arr = np.array([0,1,2,3,4,5])
arr.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [36]:
# Your code goes here
arr = np.array([0,1,2,3,4,5,6,7,8])
arr = arr.reshape((3, 3))
arr % 1 == 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 3. Create a 1D array filled with zeros and another filled with ones

In [37]:
# Your code goes here
zeros = np.zeros(5)
ones = np.ones(5)

In [38]:
zeros

array([0., 0., 0., 0., 0.])

In [39]:
ones

array([1., 1., 1., 1., 1.])

#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [40]:
# Your code goes here
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [42]:
# Your code goes here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [43]:
# Your code goes here
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b

array([5, 7, 9])

In [44]:
a * b

array([ 4, 10, 18])