# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [1]:
class Book:
    def __init__(self, title, author, pages, price):
        self.title = title
        self.author = author
        self.pages = pages
        self.price = price
    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price
        return self.price

b1 = Book('Practical Programming', 'Gries, Campbell, Montojo', 383, 50)
b2 = Book('Building a Career in Data Science', 'Robinson, Nolis', 322, 40)

#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [2]:
class Phone:
    def __init__(self, model, id, name, brand, price):
        self.model = model
        self.id = id
        self.name = name
        self.brand = brand
        self.price = price

    def get_model(self):
        return self.model
    def set_model(self, model):
        self.model = model
        return self.model

    def get_id(self):
        return self.id
    def set_id(self, id):
        self.id = id
        return self.id

    def get_name(self):
        return self.name
    def set_name(self, name):
        self.name = name
        return self.name

    def get_brand(self):
        return self.brand
    def set_brand(self, brand):
        self.brand = brand
        return self.brand

    def get_price(self):
        return self.price
    def set_price(self, price):
        self.price = price
        return self.price

    def calculate_total(self, tax):
        return self.price + (self.price * tax)

## Numpy

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

print(arr.ndim)

print(arr.shape)

print(arr.dtype)

print(arr.size)

print(arr.itemsize)

print(arr.nbytes)

print(arr.strides)

print(arr.data)

print(arr.flags)

print(arr.ctypes)

print(arr.base)

print(arr.view())

print(arr.copy())

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
int64
5
8
40
(8,)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

None
[1 2 3 4 5]
[1 2 3 4 5]


#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.reshape(2, 3)
print(arr)
print(arr.shape)
print(arr.ndim)

[[0 1 2]
 [3 4 5]]
(2, 3)
2


#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [7]:
true_arr = np.ones((3, 3), dtype=bool)
print(true_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### 3. Create a 1D array filled with zeros and another filled with ones

In [8]:
zero_arr = np.zeros(10)
one_arr = np.ones(10)
print(zero_arr)
print(one_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [9]:
arr = np.arange(10)
print(arr)
print(arr[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a, b)))

[1 2 3 4 5 6]


#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]
